[package]
name = "wrkwrk"
version = "0.2.0"
edition = "2021"

[dependencies]
reqwest = "0.11.12"
lazy_static = "1.4.0"

[dependencies.serde]
version = "1.0.148"
features = ["derive"]

[dependencies.mlua]
version = "0.8.6"
features = ["luajit", "serialize", "send", "vendored", "async", "macros"]

[dependencies.clap]
version = "4.0.8"
features = ["derive"]

[dependencies.tokio]
version = "1.21.2"
features = ["full"]
